-- Better-Auth standard tables (PostgreSQL).
-- Generated by hand from the Better-Auth schema spec; re-run
-- `npx @better-auth/cli generate` against relay/src/auth.ts on version bumps
-- and reconcile any drift.
--
-- BridgeHook customizations on `user`:
--   • plan          — billing state mirror of subscriptions.status
--   • trial_ends_at — 7-day trial deadline
--
-- All migrations in this set are additive; never edit a committed migration.

CREATE TABLE IF NOT EXISTS "user" (
  id              text PRIMARY KEY,
  name            text NOT NULL,
  email           text NOT NULL UNIQUE,
  email_verified  boolean NOT NULL DEFAULT false,
  image           text,
  created_at      timestamptz NOT NULL DEFAULT now(),
  updated_at      timestamptz NOT NULL DEFAULT now(),
  plan            text NOT NULL DEFAULT 'trialing',
  trial_ends_at   timestamptz
);

CREATE TABLE IF NOT EXISTS "session" (
  id          text PRIMARY KEY,
  token       text NOT NULL UNIQUE,
  user_id     text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  expires_at  timestamptz NOT NULL,
  ip_address  text,
  user_agent  text,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS session_user_id_idx ON "session" (user_id);

CREATE TABLE IF NOT EXISTS "account" (
  id                          text PRIMARY KEY,
  account_id                  text NOT NULL,
  provider_id                 text NOT NULL,
  user_id                     text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
  access_token                text,
  refresh_token               text,
  access_token_expires_at     timestamptz,
  refresh_token_expires_at    timestamptz,
  scope                       text,
  id_token                    text,
  password                    text,
  created_at                  timestamptz NOT NULL DEFAULT now(),
  updated_at                  timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS account_user_id_idx ON "account" (user_id);

CREATE TABLE IF NOT EXISTS "verification" (
  id          text PRIMARY KEY,
  identifier  text NOT NULL,
  value       text NOT NULL,
  expires_at  timestamptz NOT NULL,
  created_at  timestamptz DEFAULT now(),
  updated_at  timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS verification_identifier_idx ON "verification" (identifier);
